language: node_js
dist: trusty
git:
  depth: 1
cache:
  edge: true
  directories:
    - node_modules
    - "$(npm root -g)"
    - "$(npm config get prefix)/bin"
branches:
  only:
    - master
    - stage
    - test
    - dev
env:
  global:
    # CODECLIMATE_REPO_TOKEN=[secure]
    - secure: "fRdlX4tG3L7ZI1DOnbMuwYXRCUL10wgQkhXhbuxEr93M7n0SLF7PlFMizAUffpwRqGR2U0SG+MQlVa04+15aHBM591DVcb9IqXGQpVsyJvgvMq9m2uAyxw+/+KdNpI/G8UvRi/9poL1DDYvUgMeDmA4c1narClPTUZjv14ExCHBBZruw8AGvDwH58HSFSGiSYMz6E7jBkFddTq974EMRxiCKG7+tdrk5d5To6FP3N5MbhQs2Mb3JZZHyoyKsMnQMue59Elpqsp1iaIUVbeSAqexArMWspAhx0VjXNO9aOVaK3zcCU7X45sBWvTUdj3jDGfxzDq4YlBDyGUWIweb8pz64PsPC8MVl9ocphkk4iVKi941nFcdVDHAFoS2rMVriIUo4OgtbxfE5G//EVb3cJTDkLXdyZ4uIZ0t1KCQeIeAAh4j2VrfQjgQTGYoTXcd31Ge+BM2VNl2QIWHmkPrgCVf4JZBDRd9tFhTxwYBMHWrpMDT8JYetrRMrI50hiv/CWQHxwAuBE0dW8csEU9WPMgFm+TZy/qNes3BpXb+KjiVfvsW3+Ag9LgQwdzgr0/s5RI9wMPh5lwDOImeXr1ZpF/2mA1I/ThLGN2wwTr4ArpC7kDE79RtrhQarCqWYmVrEdxJMfuEWL61lrKbSc4Qxg5snWamKkq/n0qQ9s5HXK2U="
    # AWS_DEFAULT_REGION=[secure]
    - secure: "dnoGWOYOCrjSkRvTbBHql+7NLkcp/SpGguzCh2U4Ztw+WmtkJ3JhFUSOIkg3XvY2sHtjzNiuyAY0LSDiAYPzNAkgJteEho8rXx38gvXe3cE2BcZhEBJbsypmVO30svtj3+4DXosTqPJ1fGmno+k2EOsz6OL4qbykx0kfvOdcE6Lri0XIWhWu/PYPdhJZ+3KV9lIEo0G1ubvPMnnPuhbs0Gs0VqqtGa1zkDXElzZ8Xr0ufe+CkHrHshSZVjgWpcR7Dra1Dwjag0n+K/Gzbt34Vy7W5VYeuXpDXUA2HrYWUiWeS6KrNF8wf8z6dqdPGpiZzn5UXEfDy/etC6ReSSqduCP8mpYp7w4Grd/tn/AFJC80TvNx1Hf6fvMxySNrjA8fvXmTTJHfG+SgGwHQy3fuKMOQrd+LgwXLEIpU2y8ZhqAGHkHp7/OffPgRFTbVShcW/7X5Ppp+mP6CcAipYpMS9wOGnzcWKEOgv8xZN2+Mv3rv7TWIboASZJL6mzddiQlnh2ge+YUZheTie430UWVbIYvXCf9yIp9aQj96d3kTrqdbkEaWxL/DhFR8slEyUOTKATUsY3vqHmP6d/j+qP3ruRvQk1pCY18iar+cdQ1CuemW35UbvajFu7BB25xT5pmpWBfk0txeosNvednRFGp7oDQnGqXICsxGzo5E6Ekjfbs="
    # AWS_ACCESS_KEY_ID=[secure]
    - secure: "Z5rdeaOzkRdjv2ygh2M4yFg3UT7SFtv7nNiWjT+5ivV2gDVw3IxNFSEFp8M+sMeyDKPM40+c6zb5iagXnXpo0cWJQf6VafQX9keKFCYiJZXM8/7xvJANVun1sJfEn/n51LGwlLBMg5fUKLefTHciOedr6OBh0+IDva0h64VWiNRgEnph6plHDaL2y887a9bj6qcy8PIF2V7lr6AiPS7y7IS70p4D45DEQLjGWaFzk+P/t1Ra2GCFAzD9j6lyvJpT3VPCA34FCzGV+hO+gsxOqrjlPwpKdeXIpT8jStr8Mz3l6WxmjQ/CI5NVMiyiTxywZrfPKBapn3B150hjcgrxa77zM/zQDPTYzqJ0/ocSLy1A6hKWpKWtWvJvrSMxMfwJU6TbkQQ8Nx1H80XdDW0eWFyOH+cK4yskJV7lmwCOj7Q9azkqMDxC95fBbdNqLsWoxiwPkE1p/C//pQp9GpfNeN9M7z5SceiotkqtWtBVcno3lkNwBOPnu8u6U/tlSxStQ4ckvdQn/qwE5NwEZxrS3EOkbLSc3S+yjYF0uBLFw/JGbE6EGrLr6g6MnLsSXb9rn8eam8p5SFC+ddfTQvEs6EEbTHdO60OmQTFlwssBMXlx5RmzcTfSzfkg4Yhxi4wdvNFIkprMxbfLZ3UidJ6os/8+uXWXCQ4bpVzJePNVQoc="
    # AWS_SECRET_ACCESS_KEY=[secure]
    - secure: "DTOF+Xqg9jzH1OucEOCu11Zp0V3WBciKx+QF7CM8hM5QkNOer3aOyymv/auTaiLqSyCPqoo3HTLpdYiKBhKRfIj95jWuBGH8GPtURQfPTT1kOriCUCyKYr3LQgEaTEp8NH9ccCiY5Qb+fomvpg/dRejdG7AMwzTpy8UTBHN1rd01KfvmfTWLptq9744vWJZuRRo/WY0xxh5jQd1fxfwiAZnpWtvOhIfMGsWn0l+OUpcXL9JdhN/YBCfnGTDiQgAS9cGYn27RLYwMIPFl/zkkOjYCNBXlxyIxVqKhAuR8/20DC9/ROObE3wmAFCIWgx2yBNlGr/AgpQ6y5/3DXjJDLiM6X0hQjUGlGy9oMv1lJt63DeJnELwwR1vPWepmF1O1wPPGiGpyW7NVKirzET82qs5X41hFJ5yBLCcorj62Z+ThKMAmhGJNiJoVynbWmDjsa7RVfkSKMqKKcPLlqrfMjEDLAMlA50Ib55aJle7yRIc36v2URZ+3LPr+a4303c16lmhohB4KyM+474+im7D8NfYufJ2BbAPh+Mi+UoSfVobDHa7lbbQI5TG5q7wazMQTAqA7kB0r9J7LG5+M87VZP+7TNptsarBfERk7HkRi9nw0mEfQjff8FYwYxtBDFtSA+51IqnYMzi3lgT3uZ52CcDPYzfJCceJPfPRz3WiDDBY="

stage: "Run Unit Tests :clipboard:"
node_js:
  - 6
  - 8
before_install:
  - bash bin/travis-init.sh
script:
  - recink run unit -c recink-codeclimate -c recink-snyk
