language: node_js
sudo: required
node_js:
  - '4.3'
  - '6.2'
cache:
  edge: true
  directories:
    - $(npm root -g)
    - node_modules
    - deep_modules
    - $(npm config get prefix)/bin
branches:
  only:
    - master
    - dev
    - stage
    - test
before_install:
  - cp bin/test/package.json .
after_success:
  - npm run coverage
env:
  matrix:
    - TEST_SUITE=backend
    - TEST_SUITE=frontend
  global:
    - secure: 
        NAdPvpG4O8G0UL5Mc8CWmWLmpZxqquNu+k61GR4ozC7x+HL85vcc8mOu8fmNeO2SbPH+8yovi9sxvMZZBI2sC+K23u44OrcDG3oTjLGvg+uKYlXtwKCRly/jUOXAzEehJupptm4HFb56APDRYX63pNXaXOOSEccqHNa5/MspQflj3cggGyOJ1bj71PH/eQmPOJDOQZkDDNDnfZq19dHWCEeNnAKpXpk4R9DYBhej3cXpfae+puNnjUUr1DYk6st3OsHw/lcc9OKZPRBNOGCWA7gLHCNGmX1bUtfGAZhzrjhsW8woT33/NZqPr7ICLHzpsTuCmNXx0SUKo6Ogiw+Nf4JEG06sJv9iaQD+cK0hD2zeMgs4Oaa9XE1bWYL7VuxjpMzDzJMSvBhYupQ+0UexrEMg9ze2YbDO0B2E4bx1M/33ztaoqOzqy6GCMwj7JWNO3dgKQJvM+9c6VtU8TofBNqB+ROVSFJCFGrO7qOrFGwyo3bVHyzYe7gPOzH2fmfFRdVpEbr0nLwaSB1YvqTjbu+RG7LdgVk5UoiPM7kZOYTGsWIws+hrtSVo6UPZxdWUGirvGewpV8Q7BzduK4urQ6UjDiFqfz4Cx+c1I+fxUW7ZieHhsEsziKU7M9cTQQ5fmELH3HlJDyWd6ME/NQXNHae0K/IpdsFoT+FC25Iu+Cww=
    - secure: 
        SxP109CtOeuBjYKz8WEP1wyXWAi7JGAsff20fYe4CjRRgn2tPZ4cvFaUdblMImp/eRdmH3p5JWkm9LbI/FQr/UyJVNA7MeqOylb8BV2zgT85/oee8xYMUbOL+0nq+MDXh8eBiulQCcyP2WpKzLN6hIUUiYs3bOQem5YD/w1G4h1AC3/AhtKlUP8GB4wHx0nbkqbls2IdRRWwB1BA5HPE2MBr7IADSfmuC3p/rWAWKXlTR/Evrbj2YwhbN6HJdrJR0Ijrpy5pA2VcHm2pNk4AC8kJef6aPaPQZ+k2SkGkma+zU3fDLsSbbhJL0v96VAaI8XGuBYivYXf86SY4hZds3xO6F0hRujamnEYtcwptXalEZP0/WAO3NQ9pxaIa4nGj/B1nR6EN7JTEaDznR2BiQceVyzNdt6FgfwVIYZUQZ5eDE/xglEbP8tRqt0Z1TiJiuSLGc+mOl3jLjhCP58WHxjzN71ksapLZpylhlnlpjEbMlO6sdZIaIKlc8s38azqXvQ+4J6LA59NRPnfAZbGUgAHW5dUzPg8YrRlDdv54umqEB/cFETTm6Z9r7Bn68D72SD8uOUQP5Cx0w9cIKZtkGs9J6xUv+/oh6oEkrgWLq0K80XL24AU051S806yjh/ADl7VeBGClj5p9JdC2WYGJ06N23wmNoVvEROzkJo1/5ls=
notifications:
  slack:
    secure: 
      V82TJsFHbmVgD34fqV0HBreCnP7Iyj4X2HIAfN3ZdEHSv6Ct744eNrp1heze8wlE9a9zPZzA6AeX+JswnjXh5jOZfpBwQiiBTQNX3NFmQTp5z+PYT1xasL0EAAS5YWwPD0naLFl/5vR8WjWWgB+m4DmQVcTO+NcUnHuBNHOPz/1Ou/um2sJ+7m9BHYOX6j+ZPZ43n2gXKB2sKWs+O4chxwmOOavTf2/uf047B+BPATwdU7IrEMzJOOOLUxS/OdCvcs/9QEVQIhYX+6A2zAwRTwO1JIuvWsatU0Gd8KIddS5v604aGGYlJ+7vZ8pA9eDpRESBW+uHVymbrpvN6z6Nyna8wJ8YM2dm/Z20mBACq9y3PJ9KQDrwWO9e7QpSKLDTCosDV7c7yRc6F3yeUtXXO4c/bD+IAIgmUWtPEFKS+4G/ZOHTDNRm9jSfUAXDtFhkrPvCH+Ozm+DYpUhhHKxC9SoabcM/4i4dHkii8PpsXWz6/ZXEWyOxIdoUeI1cVDWQRBJ6D2hisBUIu+3FyW2ITgrCOnAWm2wXvX2z3R6qjAbcmCRREkR3UVy5wx7KidN3Ytj9sZdsuA7JH0I+TalHZM6zZU29rBe3pl80yCHNA4ePSAJkx5zBOFOZ2cdlsroipuxi6+4NCHWkznl2rNv9CIXZR9nCtCca8LgphC9ueDs=
